//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardEng.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAMCServices
    {
        public int AMCServiceId { get; set; }
        public int AMCId { get; set; }
        public System.DateTime ServviceDate { get; set; }
        public Nullable<System.DateTime> ServiceOverrideDate { get; set; }
        public string OverrideReason { get; set; }
        public string ServiceRemarks { get; set; }
        public string ServiceReportNo { get; set; }
        public Nullable<int> ServiceEngineerId { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsSystemGenerated { get; set; }
    
        public virtual tblAMC tblAMC { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
