//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardEng.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAMCQDetail
    {
        public int AMCQDetailId { get; set; }
        public int AMCQId { get; set; }
        public int MachineTypeId { get; set; }
        public int MachineModelId { get; set; }
        public string MachineSerialNo { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
        public decimal TotalAmount { get; set; }
        public string Description { get; set; }
    
        public virtual tblAMCQuotation tblAMCQuotation { get; set; }
        public virtual tblMachineModels tblMachineModels { get; set; }
        public virtual tblMachineType tblMachineType { get; set; }
    }
}
