//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardEng.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAMC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAMC()
        {
            this.tblAMCServices = new HashSet<tblAMCServices>();
        }
    
        public int AMCId { get; set; }
        public int AMCQuotationId { get; set; }
        public int CustomerId { get; set; }
        public int MachineModelId { get; set; }
        public int MachineTypeId { get; set; }
        public string MachineSerialNo { get; set; }
        public string AMCQuotationNo { get; set; }
        public decimal ActualAmount { get; set; }
        public decimal GSTPercentage { get; set; }
        public decimal GSTAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public string Remarks { get; set; }
        public System.DateTime AMCStartDate { get; set; }
        public System.DateTime AMCEndDate { get; set; }
        public bool IsAMCExpired { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblAMCQuotation tblAMCQuotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAMCServices> tblAMCServices { get; set; }
    }
}
