//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardEng.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChargebleQNote
    {
        public int ChargebleQNoteId { get; set; }
        public int ChargebleQId { get; set; }
        public string NoteText { get; set; }
    
        public virtual tblChargebleQuotation tblChargebleQuotation { get; set; }
    }
}
