//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardEng.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMachinePartsQuotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMachinePartsQuotation()
        {
            this.tblMachinePartsQuotationDetail = new HashSet<tblMachinePartsQuotationDetail>();
        }
    
        public int MachinePartsQuotationId { get; set; }
        public string QuotationNo { get; set; }
        public System.DateTime QuotationDate { get; set; }
        public int CustomerId { get; set; }
        public int CustomerContactPId { get; set; }
        public string CustomerContactPContactNo { get; set; }
        public string ReportServiceNo { get; set; }
        public string InquiryNo { get; set; }
        public Nullable<System.DateTime> InquiryDate { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<int> DeliveryWeeks { get; set; }
        public string Insurance { get; set; }
        public Nullable<int> ValidityDays { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> TotalFinalAmount { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> FreightPercentage { get; set; }
        public Nullable<decimal> TotalFreightAmount { get; set; }
        public Nullable<decimal> QuotationAmount { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public Nullable<bool> IsPIGenerated { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ServiceEngineerId { get; set; }
        public string QuotationAmountInWords { get; set; }
        public Nullable<int> QuatationByUser { get; set; }
        public Nullable<bool> IsDifferentShipAddress { get; set; }
        public string CompanyName { get; set; }
        public string Addressline1 { get; set; }
        public string Addressline2 { get; set; }
        public string Addressline3 { get; set; }
        public string GSTNo { get; set; }
        public string FreightTerms { get; set; }
        public string QuotationYear { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblCustomerContactPersons tblCustomerContactPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMachinePartsQuotationDetail> tblMachinePartsQuotationDetail { get; set; }
    }
}
