//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardEng.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StandardEng.Common.CommonMessage", typeof(CommonMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories Name.
        /// </summary>
        public static string AccessoriesName {
            get {
                return ResourceManager.GetString("AccessoriesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories Name must be less than or equal to 50 characters.
        /// </summary>
        public static string AccessoriesNameLength {
            get {
                return ResourceManager.GetString("AccessoriesNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories Name is Required.
        /// </summary>
        public static string AccessoriesNameRequired {
            get {
                return ResourceManager.GetString("AccessoriesNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories SerialNo.
        /// </summary>
        public static string AccessoriesSerialNo {
            get {
                return ResourceManager.GetString("AccessoriesSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories SerialNo must be less than or equal to 50 characters.
        /// </summary>
        public static string AccessoriesSerialNoLength {
            get {
                return ResourceManager.GetString("AccessoriesSerialNoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories SerialNo is Required.
        /// </summary>
        public static string AccessoriesSerialNoRequired {
            get {
                return ResourceManager.GetString("AccessoriesSerialNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories Type.
        /// </summary>
        public static string AccessoriesType {
            get {
                return ResourceManager.GetString("AccessoriesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories Type is Required.
        /// </summary>
        public static string AccessoriesTypeRequired {
            get {
                return ResourceManager.GetString("AccessoriesTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Amount.
        /// </summary>
        public static string ActualAmount {
            get {
                return ResourceManager.GetString("ActualAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line1.
        /// </summary>
        public static string Addressline1 {
            get {
                return ResourceManager.GetString("Addressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line2.
        /// </summary>
        public static string Addressline2 {
            get {
                return ResourceManager.GetString("Addressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR Order No.
        /// </summary>
        public static string AHMNo {
            get {
                return ResourceManager.GetString("AHMNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Product Value.
        /// </summary>
        public static string AlternateProductValue {
            get {
                return ResourceManager.GetString("AlternateProductValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative ContactNo..
        /// </summary>
        public static string AlternativeContactNo {
            get {
                return ResourceManager.GetString("AlternativeContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMC Quotation Date.
        /// </summary>
        public static string AMCQuotationDate {
            get {
                return ResourceManager.GetString("AMCQuotationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsChangeStatus.
        /// </summary>
        public static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name must be less than or equal to 50 characters.
        /// </summary>
        public static string CityNameLength {
            get {
                return ResourceManager.GetString("CityNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is Required.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commissioning Date.
        /// </summary>
        public static string CommissioningDate {
            get {
                return ResourceManager.GetString("CommissioningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commissioning File.
        /// </summary>
        public static string CommissioningFileName {
            get {
                return ResourceManager.GetString("CommissioningFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No..
        /// </summary>
        public static string ContactNo {
            get {
                return ResourceManager.GetString("ContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No. is Required.
        /// </summary>
        public static string ContactNoRequired {
            get {
                return ResourceManager.GetString("ContactNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Name.
        /// </summary>
        public static string ContactPersonName {
            get {
                return ResourceManager.GetString("ContactPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Posistion.
        /// </summary>
        public static string ContactPersonPosistion {
            get {
                return ResourceManager.GetString("ContactPersonPosistion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person is Required.
        /// </summary>
        public static string ContactPersonRequired {
            get {
                return ResourceManager.GetString("ContactPersonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name must be less than or equal to 50 characters.
        /// </summary>
        public static string CountryNameLength {
            get {
                return ResourceManager.GetString("CountryNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is Required.
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name is Required.
        /// </summary>
        public static string CustomerRequired {
            get {
                return ResourceManager.GetString("CustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Discount.
        /// </summary>
        public static string DefaultDiscount {
            get {
                return ResourceManager.GetString("DefaultDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDelete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery (in No of Weeks).
        /// </summary>
        public static string DeliveryWeeks {
            get {
                return ResourceManager.GetString("DeliveryWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Weeks is Required.
        /// </summary>
        public static string DeliveryWeeksRequired {
            get {
                return ResourceManager.GetString("DeliveryWeeksRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount (%).
        /// </summary>
        public static string DiscountPercentage {
            get {
                return ResourceManager.GetString("DiscountPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch Date.
        /// </summary>
        public static string DispatchDate {
            get {
                return ResourceManager.GetString("DispatchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DispatchDate is Required.
        /// </summary>
        public static string DispatchDateRequired {
            get {
                return ResourceManager.GetString("DispatchDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEdit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Amount.
        /// </summary>
        public static string FinalAmount {
            get {
                return ResourceManager.GetString("FinalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Amount is Required.
        /// </summary>
        public static string FinalAmountRequired {
            get {
                return ResourceManager.GetString("FinalAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        public static string Freight {
            get {
                return ResourceManager.GetString("Freight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight value  must be less than or equal to 100 characters.
        /// </summary>
        public static string FreightLength {
            get {
                return ResourceManager.GetString("FreightLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Amount.
        /// </summary>
        public static string GSTAmount {
            get {
                return ResourceManager.GetString("GSTAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Number must be equal to 15 characters.
        /// </summary>
        public static string GSTLength {
            get {
                return ResourceManager.GetString("GSTLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Number.
        /// </summary>
        public static string GSTNo {
            get {
                return ResourceManager.GetString("GSTNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST (%).
        /// </summary>
        public static string GSTPercentage {
            get {
                return ResourceManager.GetString("GSTPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST (%) is Required.
        /// </summary>
        public static string GSTPercentageRequired {
            get {
                return ResourceManager.GetString("GSTPercentageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSN Code.
        /// </summary>
        public static string HSNCode {
            get {
                return ResourceManager.GetString("HSNCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSN Code  must be less than or equal to 15 characters.
        /// </summary>
        public static string HSNCodeLength {
            get {
                return ResourceManager.GetString("HSNCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSN Code is Required.
        /// </summary>
        public static string HSNCodeRequired {
            get {
                return ResourceManager.GetString("HSNCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry / Order Date.
        /// </summary>
        public static string InquiryDate {
            get {
                return ResourceManager.GetString("InquiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry Date is Required.
        /// </summary>
        public static string InquiryDateRequired {
            get {
                return ResourceManager.GetString("InquiryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry /Order No.
        /// </summary>
        public static string InquiryNo {
            get {
                return ResourceManager.GetString("InquiryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry No must be less than or equal to 50 characters.
        /// </summary>
        public static string InquiryNoLength {
            get {
                return ResourceManager.GetString("InquiryNoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry No is Required.
        /// </summary>
        public static string InquiryNoRequired {
            get {
                return ResourceManager.GetString("InquiryNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInsert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        public static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance value must be less than or equal to 100 characters.
        /// </summary>
        public static string InsuranceLength {
            get {
                return ResourceManager.GetString("InsuranceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email adress.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPL.
        /// </summary>
        public static string IPL {
            get {
                return ResourceManager.GetString("IPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPL must be less than or equal to 15 characters.
        /// </summary>
        public static string IPLLength {
            get {
                return ResourceManager.GetString("IPLLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPL is Required.
        /// </summary>
        public static string IPLRequired {
            get {
                return ResourceManager.GetString("IPLRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Commisioning ?.
        /// </summary>
        public static string IsCommisioning {
            get {
                return ResourceManager.GetString("IsCommisioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Accessories.
        /// </summary>
        public static string MachineAccessories {
            get {
                return ResourceManager.GetString("MachineAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Accessories is Required.
        /// </summary>
        public static string MachineAccessoriesRequired {
            get {
                return ResourceManager.GetString("MachineAccessoriesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Model.
        /// </summary>
        public static string MachineModel {
            get {
                return ResourceManager.GetString("MachineModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Model is Required.
        /// </summary>
        public static string MachineModelRequired {
            get {
                return ResourceManager.GetString("MachineModelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name.
        /// </summary>
        public static string MachineName {
            get {
                return ResourceManager.GetString("MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name must be less than or equal to 50 characters.
        /// </summary>
        public static string MachineNameLength {
            get {
                return ResourceManager.GetString("MachineNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name is Required.
        /// </summary>
        public static string MachineNameRequired {
            get {
                return ResourceManager.GetString("MachineNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Description.
        /// </summary>
        public static string MachinePartDescription {
            get {
                return ResourceManager.GetString("MachinePartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Parts.
        /// </summary>
        public static string MachineParts {
            get {
                return ResourceManager.GetString("MachineParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        public static string MachinePartsNo {
            get {
                return ResourceManager.GetString("MachinePartsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Parts is Required.
        /// </summary>
        public static string MachinePartsRequired {
            get {
                return ResourceManager.GetString("MachinePartsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Serial No.
        /// </summary>
        public static string MachineSerialNo {
            get {
                return ResourceManager.GetString("MachineSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Serial No is Required.
        /// </summary>
        public static string MachineSerialNoRequired {
            get {
                return ResourceManager.GetString("MachineSerialNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Type.
        /// </summary>
        public static string MachineType {
            get {
                return ResourceManager.GetString("MachineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Type is Required.
        /// </summary>
        public static string MachineTypeRequired {
            get {
                return ResourceManager.GetString("MachineTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Name.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be less than or equal to 100 characters.
        /// </summary>
        public static string NameLength {
            get {
                return ResourceManager.GetString("NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is Required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;F (%).
        /// </summary>
        public static string PAndFPercentage {
            get {
                return ResourceManager.GetString("PAndFPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part HSNCode.
        /// </summary>
        public static string PartsHSNCode {
            get {
                return ResourceManager.GetString("PartsHSNCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string PartsQuantity {
            get {
                return ResourceManager.GetString("PartsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is Required.
        /// </summary>
        public static string PartsQuantityRequired {
            get {
                return ResourceManager.GetString("PartsQuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be less than or equal to 15 characters.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Terms.
        /// </summary>
        public static string PaymentTerms {
            get {
                return ResourceManager.GetString("PaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Terms is Required.
        /// </summary>
        public static string PaymentTermsRequired {
            get {
                return ResourceManager.GetString("PaymentTermsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Length must be less than or equal to 10 characters.
        /// </summary>
        public static string PhoneLength {
            get {
                return ResourceManager.GetString("PhoneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        public static string PinCode {
            get {
                return ResourceManager.GetString("PinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code must be equal to 6 characters.
        /// </summary>
        public static string PinCodeLength {
            get {
                return ResourceManager.GetString("PinCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Commisioning Remark.
        /// </summary>
        public static string PrecommisioningRemark {
            get {
                return ResourceManager.GetString("PrecommisioningRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Commisoning Date.
        /// </summary>
        public static string PreCommisoningDate {
            get {
                return ResourceManager.GetString("PreCommisoningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Commisoning Date is Required.
        /// </summary>
        public static string PreCommisoningDateRequired {
            get {
                return ResourceManager.GetString("PreCommisoningDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type Name.
        /// </summary>
        public static string ProductTypeName {
            get {
                return ResourceManager.GetString("ProductTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type Name must be less than or equal to 50 characters.
        /// </summary>
        public static string ProductTypeNameLength {
            get {
                return ResourceManager.GetString("ProductTypeNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type Name is Required.
        /// </summary>
        public static string ProductTypeNameRequired {
            get {
                return ResourceManager.GetString("ProductTypeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Value.
        /// </summary>
        public static string ProductValue {
            get {
                return ResourceManager.GetString("ProductValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Value must be less than or equal to 50 characters.
        /// </summary>
        public static string ProductValueLength {
            get {
                return ResourceManager.GetString("ProductValueLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Value is Required.
        /// </summary>
        public static string ProductValueRequired {
            get {
                return ResourceManager.GetString("ProductValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit-Margin (%).
        /// </summary>
        public static string ProfitMarginPercentage {
            get {
                return ResourceManager.GetString("ProfitMarginPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Date.
        /// </summary>
        public static string QuotationDate {
            get {
                return ResourceManager.GetString("QuotationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Date is Required.
        /// </summary>
        public static string QuotationDateRequired {
            get {
                return ResourceManager.GetString("QuotationDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Number.
        /// </summary>
        public static string QuotationNo {
            get {
                return ResourceManager.GetString("QuotationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Name must be less than or equal to 50 characters.
        /// </summary>
        public static string RegionNameLength {
            get {
                return ResourceManager.GetString("RegionNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Name is Required.
        /// </summary>
        public static string RegionNameRequired {
            get {
                return ResourceManager.GetString("RegionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Report No.
        /// </summary>
        public static string ReportServiceNo {
            get {
                return ResourceManager.GetString("ReportServiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name must be less than or equal to 50 characters.
        /// </summary>
        public static string RoleNameLength {
            get {
                return ResourceManager.GetString("RoleNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name is Required.
        /// </summary>
        public static string RoleNameRequired {
            get {
                return ResourceManager.GetString("RoleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price.
        /// </summary>
        public static string SellingPrice {
            get {
                return ResourceManager.GetString("SellingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Engineer.
        /// </summary>
        public static string ServiceEngineer {
            get {
                return ResourceManager.GetString("ServiceEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Engineer is Required.
        /// </summary>
        public static string ServiceEngineerRequired {
            get {
                return ResourceManager.GetString("ServiceEngineerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Name.
        /// </summary>
        public static string StateName {
            get {
                return ResourceManager.GetString("StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Name must be less than or equal to 50 characters.
        /// </summary>
        public static string StateNameLength {
            get {
                return ResourceManager.GetString("StateNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is Required.
        /// </summary>
        public static string StateRequired {
            get {
                return ResourceManager.GetString("StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STD Price.
        /// </summary>
        public static string STDPrice {
            get {
                return ResourceManager.GetString("STDPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxable Amount.
        /// </summary>
        public static string TaxablePrice {
            get {
                return ResourceManager.GetString("TaxablePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price is Required.
        /// </summary>
        public static string TotalPriceRequired {
            get {
                return ResourceManager.GetString("TotalPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price is Required.
        /// </summary>
        public static string UnitPriceRequired {
            get {
                return ResourceManager.GetString("UnitPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Address is Required.
        /// </summary>
        public static string UserAddressRequired {
            get {
                return ResourceManager.GetString("UserAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code.
        /// </summary>
        public static string UserCode {
            get {
                return ResourceManager.GetString("UserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code must be less than or equal to 3 characters.
        /// </summary>
        public static string UserCodeLength {
            get {
                return ResourceManager.GetString("UserCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code is Required.
        /// </summary>
        public static string UserCodeRequired {
            get {
                return ResourceManager.GetString("UserCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name must be less than or equal to 50 characters.
        /// </summary>
        public static string UsernameLength {
            get {
                return ResourceManager.GetString("UsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is Required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity (in no of Days).
        /// </summary>
        public static string ValidityDays {
            get {
                return ResourceManager.GetString("ValidityDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity Days is Required.
        /// </summary>
        public static string ValidityDaysRequired {
            get {
                return ResourceManager.GetString("ValidityDaysRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsView.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Expiry Date.
        /// </summary>
        public static string WarrantyExpireDate {
            get {
                return ResourceManager.GetString("WarrantyExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Period (In Months).
        /// </summary>
        public static string WarrantyPeriod {
            get {
                return ResourceManager.GetString("WarrantyPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Period is Required.
        /// </summary>
        public static string WarrantyPeriodRequired {
            get {
                return ResourceManager.GetString("WarrantyPeriodRequired", resourceCulture);
            }
        }
    }
}
